# ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    app: nginx-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
     cert-manager.io/cluster-issuer: lets-encryp-production
spec:
 tls:
 - hosts:
   - datacenter.ucol.mx
   - pre-datacenter.ucol.mx
   secretName: microbot-ingress-tls
 rules:
  - host: "datacenter.ucol.mx"
    http:
      paths:
      - pathType: Prefix
        path: /admin
        backend:
          service:
            name: phpmyadmin-service-itzel
            port:
              number: 80

      - pathType: Prefix
        path: /proyecto
        backend:
          service:
            name: proyecto-service-itzel
            port:
              number: 80

      - pathType: Prefix
        path: /simplesaml
        backend:
          service:
            name: proyecto-service-itzel
            port:
              number: 80


      - pathType: Prefix
        path: /admin2
        backend:
          service:
            name: phpmyadmin-service2
            port:
              number: 80

      - pathType: Prefix
        path: /proyecto2
        backend:
          service:
            name: proyecto2
            port:
              number: 80

      - pathType: Prefix
        path: /simplesaml2
        backend:
          service:
            name: proyecto2
            port:
              number: 80
      
      - pathType: Prefix
        path: /idp
        backend:
          service:
            name: idp
            port:
              number: 80
---
# ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: baymax
  labels:
    app: nginx-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
     cert-manager.io/cluster-issuer: lets-encryp-production
spec:
 tls:
 - hosts:
   - datacenter.ucol.mx
   - pre-datacenter.ucol.mx
   secretName: microbot-ingress-tls
 rules:

  - host: "datacenter.ucol.mx"
    http:
      paths:
      - pathType: Prefix
        path: /baymax
        backend:
          service:
            name: baymax
            port:
              number: 80

---
# ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: molina
  labels:
    app: nginx-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
     cert-manager.io/cluster-issuer: lets-encryp-production
spec:
 tls:
 - hosts:
   - datacenter.ucol.mx
   - pre-datacenter.ucol.mx
   secretName: microbot-ingress-tls
 rules:

  - host: "datacenter.ucol.mx"
    http:
      paths:
      - pathType: Prefix
        path: /cursoMolina
        backend:
          service:
            name: app-molina
            port:
              number: 80

---

# ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: cursokubernetesponcho
  labels:
    app: nginx-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
     cert-manager.io/cluster-issuer: lets-encryp-production
spec:
 tls:
 - hosts:
   - datacenter.ucol.mx
   - pre-datacenter.ucol.mx
   secretName: microbot-ingress-tls
 rules:

  - host: "datacenter.ucol.mx"
    http:
      paths:
      - pathType: Prefix
        path: /curso_devops_poncho
        backend:
          service:
            name: lolponcho
            port:
              number: 80

---
# ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: fbo
  labels:
    app: nginx-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
     cert-manager.io/cluster-issuer: lets-encryp-production
spec:
 tls:
 - hosts:
   - datacenter.ucol.mx
   - pre-datacenter.ucol.mx
   secretName: microbot-ingress-tls
 rules:

  - host: "datacenter.ucol.mx"
    http:
      paths:
      - pathType: Prefix
        path: /fbo
        backend:
          service:
            name: fboapp
            port:
              number: 80

---
# ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: myfirstapp 
  labels:
    app: nginx-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
     cert-manager.io/cluster-issuer: lets-encryp-production
spec:
 tls:
 - hosts:
   - datacenter.ucol.mx
   - pre-datacenter.ucol.mx
   secretName: microbot-ingress-tls
 rules:

  - host: "datacenter.ucol.mx"
    http:
      paths:
      - pathType: Prefix
        path: /cursonabor
        backend:
          service:
            name: myfirstapp
            port:
              number: 80

---
# ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: aplicacioncurso
  labels:
    app: nginx-ingress
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
     cert-manager.io/cluster-issuer: lets-encryp-production
spec:
 tls:
 - hosts:
   - datacenter.ucol.mx
   - pre-datacenter.ucol.mx
   secretName: microbot-ingress-tls
 rules:

  - host: "datacenter.ucol.mx"
    http:
      paths:
      - pathType: Prefix
        path: /curso
        backend:
          service:
            name: aplicacion
            port:
              number: 80

